aliases:
  - "live"
  - "mcislive"

api:
  youtube:
    enabled: true
    api-key: ""
  twitch:
    enabled: true
    client-id: ""
    client-secret: ""

check:
  interval: 120
  enabled: true

placeholders:
  twitch: "&#6441a4&lTWITCH&r"
  youtube: "&4&lYOUTUBE&r"
  live: "&c●&r"
  offline: "&7●&r"


notifications:
  enabled: true

  actionbar:
    enabled: true
    message: "&c● &7| &f{player} &fis currently streaming on {platform}"

  chat:
    enabled: true
    message: "&c● &7| &f{player} &fis currently streaming on {platform}"